// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyBNaouq1Rzc2uFEA126246wSBMDJfjtLbM",
      authDomain: "mini-projeto4.firebaseapp.com",
      databaseURL: "https://projeto-unid2-ddm-default-rtdb.firebaseio.com/",
      projectId: "projeto-unid2-ddm",
      storageBucket: "projeto-unid2-ddm.appspot.com",
      messagingSenderId: "353808495533",
      appId: "1:353808495533:android:2b1288a5489b202205a724");

  static const FirebaseOptions android = FirebaseOptions(
    apiKey:
        'AIzaSyBNaouq1Rzc2uFEA126246wSBMDJfjtLbM', // Substitua com seu valor real
    appId: '1:353808495533:android:2b1288a5489b202205a724',
    messagingSenderId: '353808495533',
    projectId: 'projeto-unid2-ddm',
    storageBucket: 'projeto-unid2-ddm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey:
        'AIzaSyBNaouq1Rzc2uFEA126246wSBMDJfjtLbM', // Substitua com seu valor real
    appId: '1:353808495533:android:2b1288a5489b202205a724',
    messagingSenderId: '353808495533',
    projectId: 'projeto-unid2-ddm',
    storageBucket: 'projeto-unid2-ddm.appspot.com',
    iosBundleId: 'com.test.projetounid2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxCYGlpcdBZQcdHoohz3WRDPW1r-WQedI',
    appId: '1:294513577416:ios:315765797dcf7a412fc4fd',
    messagingSenderId: '294513577416',
    projectId: 'projeto-de-teste-64e09',
    storageBucket: 'projeto-de-teste-64e09.appspot.com',
    iosBundleId: 'com.example.miniprojeto4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCv9y3MPKvOvPqRMUe7EmSj6Fp8nhRWAbs',
    appId: '1:294513577416:web:f041803301082a742fc4fd',
    messagingSenderId: '294513577416',
    projectId: 'projeto-de-teste-64e09',
    authDomain: 'projeto-de-teste-64e09.firebaseapp.com',
    storageBucket: 'projeto-de-teste-64e09.appspot.com',
    measurementId: 'G-D85DSH98Z9',
  );
}
